name: Run python test

on: 
    push:
      branches:
        - main
        


jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.3

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: run tests using pytest
        run: |
          pytest 